language: python
python:
  - "3.7"

git:
  depth: 1

branches:
  only:
    - master

install:
  - pip install -r requirements.txt

script:
  - python3 test/request_handler_test.py

deploy:
  provider: script
  script: pip install pysftp && python tools/deploy.py
  on:
    branch: master
